use viajes;
DELETE FROM viajes;
DELETE FROm users;

INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES
	(1, 'El Sáhara', 'Abrazado entre las arenas del Sahara y el océano Atlántico se encuentra este país, tierra de tuaregs, caravanas de camellos y misterios enterrados en las dunas.', '2026-01-23', '2026-02-01', 2100, 0, 'Solitario', 20, 'sahara.jpg'),
	(2, 'Marruecos', 'Te proponemos ir a lo local. Conocer el Marruecos más real y más auténtico posible. Si te gustan las emociones fuertes, agárrate fuerte ...', '2026-01-31', '2026-02-18', 890, 0, 'Grupo', 60, 'marruecos.jpg'),
	(3, 'Sri Lanka', 'Sri Lanka, antiguamente denominada Ceilán, alberga en su pequeño interior la belleza de templos, montañas y paisajes exuberantes. Y es que esta isla con forma de lágrima esconde un rincón para todos los gustos viajeros.', '2026-02-06', '2026-02-20', 1600, 0, 'Pareja', 30, 'sri-lanka.jpg'),
	(4, 'Omán', 'Recorrer Omán con Paso Noroeste será una experiencia que no olvidarás en la vida. ayuda', '2026-02-13', '2026-02-24', 1200, 0, 'Solitario', 55, 'oman.jpg'),
	(5, 'Etiopía', 'Tierra de paisajes montañosos y valles profundos, rica en historia antigua y tradiciones culturales únicas, con iglesias talladas en roca, tribus ancestrales y cafés reconocidos mundialmente.', '2026-02-14', '2026-02-24', 2000, 0, 'Solitario', 5, 'etiopia.jpg'),
	(6, 'Colombia', 'Colombia es uno de esos países que han sabido transformarse. De no ser aptos para viajar, se han convertido en uno de los referentes de América. Y es que Colombia tiene mucho que ofrecer: sus animadas capitales, la belleza de su zona cafetera, sus pueblos coloniales y sus idílicas playas.', '2026-02-14', '2026-03-01', 1700, 0, 'Grupo', 50, 'colombia.jpg'),
	(8, 'Nepal', 'País de montañas majestuosas, incluyendo el Everest, conocido por sus monasterios budistas, templos hindúes y rutas de trekking que ofrecen aventuras y espiritualidad en cada paso.', '2026-02-28', '2026-03-20', 2000, 0, 'Grupo', 100, 'nepal.jpg'),
	(9, 'Filipinas', 'Archipiélago tropical con playas de arena blanca, aguas cristalinas y biodiversidad marina impresionante, famoso por su cultura festiva, pueblos coloridos y hospitalidad cálida.', '2026-02-27', '2026-03-22', 1700, 1, 'Pareja', 30, 'filipinas.jpg'),
	(10, 'Islandia', 'Si buscas una aventura en un corto periodo de tiempo, estás en el lugar adecuado. Ven a explorar la tierra de los vikingos, recorre el círculo dorado con su geiser Strokkur y su cascada Gulfoss, sumérgete en una piscina termal en un solitario valle rodeado de montañas, pasea por arena negra o por el hielo de un glaciar y contempla los icebergs flotando en la laguna de Jokulsarlong.', '2026-03-02', '2026-03-23', 1100, 0, 'Solitario', 25, 'islandia.jpg'),
	(12, 'París', 'Una experiencia pensada para compartir momentos especiales recorriendo calles históricas, cafés emblemáticos y monumentos icónicos. El viaje combina cultura, gastronomía y tiempo libre para disfrutar de la ciudad a vuestro ritmo, creando recuerdos únicos en un entorno inigualable.', '2026-02-10', '2026-02-17', 4900, 1, 'Pareja', 20, 'paris.jpg'),
	(13, 'Japón', 'Ruta cultural que mezcla tradición y modernidad a través de templos, barrios históricos y ciudades vibrantes. El viajero descubrirá costumbres ancestrales, gastronomía local y paisajes serenos, todo acompañado de una organización cuidada para una inmersión auténtica.', '2026-04-01', '2026-04-14', 3200, 1, 'Grupo', 25, 'japon.jpeg'),
	(14, 'Patagonia', 'Aventura enfocada en la exploración de uno de los territorios más impresionantes del planeta. Montañas, glaciares y lagos infinitos acompañan un viaje exigente pero gratificante, ideal para amantes del senderismo, la fotografía y la naturaleza en estado puro.', '2026-01-20', '2026-02-02', 3500, 0, 'Grupo', 18, 'patagonia.jpg'),
	(15, 'Toscana', 'Recorrido tranquilo por pueblos medievales, viñedos y paisajes rurales donde el tiempo parece detenerse. Perfecto para disfrutar de la gastronomía local, vinos reconocidos y paseos relajados, combinando cultura, descanso y experiencias auténticas en un entorno acogedor.', '2026-05-10', '2026-05-18', 2100, 0, 'Pareja', 22, 'toscana.jpg'),
	(16, 'Nueva Zelanda', 'Viaje orientado a descubrir escenarios espectaculares entre montañas, fiordos y costas salvajes. Pensado para viajeros que buscan aventura moderada, paisajes cinematográficos y contacto constante con la naturaleza, todo con una planificación que maximiza cada jornada.', '2026-03-18', '2026-04-02', 3700, 0, 'Solitario', 12, 'nueva-zelanda.jpeg'),
	(17, 'Egipto', 'Experiencia cultural centrada en la historia antigua, recorriendo templos, pirámides y ciudades legendarias. El viaje ofrece contexto histórico, visitas guiadas y tiempo para asimilar la magnitud de una civilización que sigue despertando fascinación en todo el mundo.', '2026-02-05', '2026-02-14', 2400, 1, 'Grupo', 30, 'egipto.jpg'),
	(18, 'Bali', 'Estancia enfocada en el equilibrio personal, la cultura local y la naturaleza exuberante. Ideal para quienes buscan un viaje introspectivo, con templos, arrozales y momentos de calma, combinando actividades suaves con tiempo libre para la reflexión personal.', '2026-06-01', '2026-06-12', 2300, 1, 'Solitario', 14, 'bali.jpg'),
	(19, 'Nueva York', 'Inmersión completa en una de las ciudades más dinámicas del mundo. El viaje combina visitas a iconos culturales, barrios diversos y tiempo libre para explorar según intereses personales, ofreciendo una experiencia intensa, variada y perfectamente organizada.', '2026-03-01', '2026-03-08', 2000, 1, 'Grupo', 35, 'nueva-york.jpg'),
	(20, 'Escocia', 'Ruta que recorre castillos, paisajes verdes y pueblos con fuerte identidad cultural. Pensado para disfrutar de la historia, la música tradicional y la naturaleza, el viaje equilibra visitas guiadas con trayectos escénicos y momentos de descanso.', '2026-04-20', '2026-04-30', 2600, 0, 'Pareja', 16, 'escocia.jpg'),
	(21, 'Canadá', 'Viaje enfocado en grandes espacios naturales, parques nacionales y fauna en libertad. Ideal para quienes buscan tranquilidad, rutas panorámicas y actividades al aire libre, disfrutando de un entorno seguro, organizado y visualmente impresionante.', '2026-06-15', '2026-06-30', 3400, 0, 'Solitario', 10, 'canada.jpg'),
	(22, 'Grecia', 'Recorrido cultural que une historia antigua, paisajes mediterráneos y gastronomía local. Pensado para disfrutar en compañía, el viaje ofrece equilibrio entre visitas a yacimientos históricos, paseos costeros y tiempo libre en entornos tradicionales.', '2026-05-20', '2026-05-30', 2500, 1, 'Pareja', 20, 'grecia.jpg'),
	(23, 'Perú', 'Experiencia centrada en civilizaciones precolombinas, paisajes andinos y tradiciones vivas. El viaje combina rutas culturales, caminatas moderadas y gastronomía local, ofreciendo una visión profunda del país con una organización pensada para el viajero.', '2026-07-01', '2026-07-15', 3100, 1, 'Grupo', 26, 'peru.jpg'),
	(24, 'Noruega', 'Viaje pensado para contemplar paisajes del norte europeo entre fiordos, montañas nevadas y pueblos costeros. Ideal para quienes buscan tranquilidad, naturaleza imponente y experiencias únicas como avistamiento de auroras boreales, recorridos escénicos y contacto directo con entornos poco alterados.', '2026-01-10', '2026-01-20', 3300, 0, 'Solitario', 12, 'noruega.jpg'),
	(25, 'Portugal', 'Escapada perfecta para disfrutar del océano Atlántico, ciudades con encanto y una gastronomía muy cuidada. El viaje combina paseos relajados, visitas culturales y tiempo libre para compartir experiencias, creando un equilibrio ideal entre descanso y descubrimiento.', '2026-06-05', '2026-06-13', 1800, 1, 'Pareja', 24, 'portugal.jpg');
    
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES
    (26, 'Argentina', 'Descubre la diversidad de Argentina, desde los glaciares de la Patagonia hasta los Andes y la Pampa. Explora ciudades como Buenos Aires y pueblos con encanto, disfruta del tango, gastronomía local y vinos reconocidos. Naturaleza, cultura y aventura se combinan en un viaje único e inolvidable.', '2026-07-10', '2026-07-25', 2800, 0, 'Grupo', 30, 'argentina.jpg'),
    (27, 'Brasil', 'Brasil ofrece selvas, playas y ciudades vibrantes como Río de Janeiro. Vive la cultura local, música, danza y festivales coloridos. Disfruta de la Amazonía, excursiones costeras y la hospitalidad brasileña mientras exploras mercados, barrios históricos y reservas naturales. Una experiencia intensa de naturaleza, cultura y diversión.', '2026-08-01', '2026-08-15', 2500, 0, 'Pareja', 25, 'brasil.jpg'),
    (28, 'Chile', 'Chile combina desiertos, montañas, glaciares y bosques. Explora Santiago, Valparaíso y la Patagonia, disfrutando de paisajes espectaculares y cultura local. Gastronomía, tradiciones y naturaleza se entrelazan, ofreciendo caminatas, excursiones y aventuras al aire libre, ideales para quienes buscan experiencias diversas en un país largo y sorprendente.', '2026-09-05', '2026-09-20', 2700, 0, 'Solitario', 15, 'chile.jpg'),
    (29, 'Australia', 'Australia fascina con sus playas, desiertos, selvas y ciudades modernas. Descubre Sídney y Melbourne, explora la Gran Barrera de Coral y los paisajes del outback. Cultura aborigen, fauna única y aventuras al aire libre se combinan en un viaje diverso, lleno de descubrimientos, emoción y paisajes impresionantes.', '2026-10-01', '2026-10-18', 4000, 0, 'Grupo', 20, 'australia.jpg'),
    (30, 'Vietnam', 'Vietnam mezcla historia, cultura y paisajes sorprendentes, desde ríos y arrozales hasta playas paradisíacas. Descubre ciudades históricas, mercados locales y templos antiguos. La gastronomía, la hospitalidad de su gente y los recorridos naturales ofrecen una experiencia equilibrada entre cultura, aventura y relajación, perfecta para viajeros curiosos y exploradores.', '2026-07-12', '2026-07-26', 1800, 0, 'Pareja', 30, 'vietnam.jpg'),
    (31, 'Tailandia', 'Tailandia ofrece templos, selvas y playas tropicales. Descubre Bangkok y Chiang Mai, disfruta de la gastronomía local, mercados y festivales tradicionales. Aventuras al aire libre, excursiones en barco y experiencias culturales se combinan con momentos de relax en sus costas paradisíacas, creando un viaje diverso, auténtico y memorable.', '2026-08-15', '2026-08-30', 2200, 0, 'Solitario', 20, 'tailandia.jpg'),
    (32, 'India', 'India asombra con su riqueza cultural, templos, palacios y diversidad de paisajes. Desde el Taj Mahal hasta el Himalaya, descubre tradiciones, mercados y gastronomía única. Experiencias espirituales y culturales se mezclan con aventura y exploración, ofreciendo un viaje intenso, lleno de colores, aromas, historia y momentos inolvidables para todos los sentidos.', '2026-09-01', '2026-09-18', 2600, 1, 'Grupo', 40, 'india.jpg'),
    (33, 'China', 'China combina historia milenaria, templos, ciudades modernas y paisajes naturales impresionantes. Explora Beijing, Shanghai y la Gran Muralla, disfruta de la gastronomía local y la riqueza cultural de cada región. Desde montañas hasta ríos y antiguos pueblos, la mezcla de tradición y modernidad crea un viaje fascinante y variado.', '2026-10-05', '2026-10-22', 3000, 1, 'Pareja', 25, 'china.jpg'),
    (34, 'Turquía', 'Turquía ofrece historia, cultura y paisajes entre Europa y Asia. Descubre Estambul, Capadocia y la Riviera Turca, disfrutando de mercados, mezquitas y antiguas ruinas. La gastronomía, la hospitalidad local y las excursiones por paisajes únicos crean una experiencia completa que combina aventura, cultura y relax en un solo viaje.', '2026-06-10', '2026-06-20', 2000, 0, 'Solitario', 18, 'turquia.jpg'),
    (37, 'Suiza', 'Suiza combina montañas, lagos y ciudades llenas de historia y cultura. Descubre los Alpes, pasea por Zúrich, Ginebra y Lucerna, disfruta de gastronomía local y paisajes impresionantes. Actividades al aire libre, senderismo y excursiones se mezclan con cultura urbana, creando un viaje equilibrado, visualmente impactante y memorable.', '2026-09-10', '2026-09-22', 3500, 1, 'Solitario', 15, 'suiza.jpg'),
    (42, 'Italia', 'Italia combina arte, historia, gastronomía y paisajes variados. Descubre Roma, Florencia y la Toscana, disfruta de museos, monumentos y viñedos. Las ciudades vibrantes, pueblos medievales y paisajes naturales ofrecen un viaje completo, equilibrando cultura, relax y experiencias gastronómicas únicas en un entorno histórico y visualmente impresionante.', '2026-09-01', '2026-09-12', 2500, 0, 'Grupo', 30, 'italia.jpg'),
    (45, 'Corea del Sur', 'Corea del Sur fascina con ciudades modernas, templos antiguos y paisajes naturales. Explora Seúl, Busan y la campiña, disfruta de gastronomía, cultura pop y tradiciones milenarias. La mezcla de modernidad, historia y naturaleza crea un viaje intenso y diverso, lleno de descubrimientos, experiencias culturales y momentos inolvidables.', '2026-08-15', '2026-08-28', 3100, 0, 'Grupo', 25, 'corea-sur.jpg');

INSERT INTO `users` (`user`, `pass`, `email`, `admin`, `card`, `cardnum`) VALUES
	('admin', 'admin', 'admin@easypeasytravel.com', 1, "0000 0000 0000 0000", 111);