use viajes;
DELETE FROM viajes;
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (1, 'El Sahara', 'Abrazado entre las arenas del Sahara y el océano Atlántico se encuentra este país, tierra de tuaregs, caravanas de camellos y misterios enterrados en las dunas.', '2026-01-23', '2026-02-01', 2100, 1, 'Solitario', 20, 'https://visitamarruecos.com/wp-content/uploads/2020/09/pexels-taryn-elliott-4253829.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (2, 'Marruecos', 'Te proponemos ir a lo local. Conocer el Marruecos más real y más auténtico posible. Si te gustan las emociones fuertes, agárrate fuerte ...', '2026-01-31', '2026-02-18', 890, 1, 'Grupo', 60, 'https://blogger.googleusercontent.com/img/a/AVvXsEgBssa8kocHYJwKngT0zQsKJiEztQAHqPuZRI4FppknwGqGRp1avEWtP5l1cqT8Jsz1j5gCZUl3hMAeZ7_7T2WLAG_umhWkiSbVmdodLZUeq4G7uw4N8BoRIU5hZQkcxT7juhOLYH5CBrWelhX_tmcgsFkeoi42PkSlpOyL3sOQgFVbXJst_Bf5zMf04w=w640-h426');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (3, 'Sri Lanka', 'Sri Lanka, antiguamente denominada Ceilán, alberga en su pequeño interior la belleza de templos, montañas y paisajes exuberantes. Y es que esta isla con forma de lágrima esconde un rincón para todos los gustos viajeros.', '2026-02-06', '2026-02-20', 1600, 1, 'Pareja', 30, 'https://tdviajes.net/wp-content/uploads/2025/12/The_nine_arch.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (4, 'Omán', 'Recorrer Omán con Paso Noroeste será una experiencia que no olvidarás en la vida.', '2026-02-13', '2026-02-24', 1200, 1, 'Solitario', 10, 'https://strapi-imaginary.weroad.it/resource/medium/926/ciudad-blanca-valle-montana-rocoso-atardecer-brumoso.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (5, 'Etiopía', 'Tierra de paisajes montañosos y valles profundos, rica en historia antigua y tradiciones culturales únicas, con iglesias talladas en roca, tribus ancestrales y cafés reconocidos mundialmente.', '2026-02-14', '2026-02-24', 2000, 1, 'Solitario', 5, 'https://i0.wp.com/www.exoticca.com/wp-content/uploads/2019/06/17-curiosidades-de-Etiopia-que-debes-conocer-antes-de-ir-1.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (6, 'Colombia', 'Colombia es uno de esos países que han sabido transformarse. De no ser aptos para viajar, se han convertido en uno de los referentes de América. Y es que Colombia tiene mucho que ofrecer: sus animadas capitales, la belleza de su zona cafetera, sus pueblos coloniales y sus idílicas playas.', '2026-02-14', '2026-03-01', 1700, 1, 'Grupo', 50, 'https://blog.centraldereservas.com/wp-content/uploads/2022/01/Que-ver-en-Colombia.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (8, 'Nepal', 'País de montañas majestuosas, incluyendo el Everest, conocido por sus monasterios budistas, templos hindúes y rutas de trekking que ofrecen aventuras y espiritualidad en cada paso.', '2026-02-28', '2026-03-20', 2000, 1, 'Grupo', 100, 'https://epictravels.cl/wp-content/uploads/2025/04/nepal.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (9, 'Filipinas', 'Archipiélago tropical con playas de arena blanca, aguas cristalinas y biodiversidad marina impresionante, famoso por su cultura festiva, pueblos coloridos y hospitalidad cálida.', '2026-02-27', '2026-03-22', 1700, 1, 'Pareja', 30, 'https://blackpepper.travel/cache/2023-12/viajes-filipinas-blackpepper-2-0010-galeria-2x-1181x786.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES (10, 'Islandia', 'Si buscas una aventura en un corto periodo de tiempo, estás en el lugar adecuado. Ven a explorar la tierra de los vikingos, recorre el círculo dorado con su geiser Strokkur y su cascada Gulfoss, sumérgete en una piscina termal en un solitario valle rodeado de montañas, pasea por arena negra o por el hielo de un glaciar y contempla los icebergs flotando en la laguna de Jokulsarlong.', '2026-03-02', '2026-03-23', 1100, 1, 'Solitario', 25, 'https://academiaplay.net/wp-content/uploads/2022/07/Islandia-2.jpg');
INSERT INTO `viajes` (`id`, `titulo`, `descripcion`, `fecha_inicio`, `fecha_fin`, `precio`, `destacado`, `tipo`, `plazas`, `url_imagen`) VALUES
(12, 'París', 'Una experiencia pensada para compartir momentos especiales recorriendo calles históricas, cafés emblemáticos y monumentos icónicos. El viaje combina cultura, gastronomía y tiempo libre para disfrutar de la ciudad a vuestro ritmo, creando recuerdos únicos en un entorno inigualable.', '2026-02-10', '2026-02-17', 1900, 1, 'Pareja', 20, 'https://cdn2.civitatis.com/francia/paris/galeria/torre-eiffel-altura.jpg'),
(13, 'Japón', 'Ruta cultural que mezcla tradición y modernidad a través de templos, barrios históricos y ciudades vibrantes. El viajero descubrirá costumbres ancestrales, gastronomía local y paisajes serenos, todo acompañado de una organización cuidada para una inmersión auténtica.', '2026-04-01', '2026-04-14', 3200, 1, 'Grupo', 25, 'https://tr2storage.blob.core.windows.net/imagenes/nIoLCK5zpYF6-chC14sr9qfjpeg.jpeg'),
(14, 'Patagonia', 'Aventura enfocada en la exploración de uno de los territorios más impresionantes del planeta. Montañas, glaciares y lagos infinitos acompañan un viaje exigente pero gratificante, ideal para amantes del senderismo, la fotografía y la naturaleza en estado puro.', '2026-01-20', '2026-02-02', 3500, 1, 'Grupo', 18, 'https://images.ctfassets.net/m5us57n7qfgl/5xT4hfqq0WO3uxjkIjKBOS/5c90cce3a084f72d63a5740d95f2ddb2/Fizt-roy-patagonia-host.jpg'),
(15, 'Toscana', 'Recorrido tranquilo por pueblos medievales, viñedos y paisajes rurales donde el tiempo parece detenerse. Perfecto para disfrutar de la gastronomía local, vinos reconocidos y paseos relajados, combinando cultura, descanso y experiencias auténticas en un entorno acogedor.', '2026-05-10', '2026-05-18', 2100, 1, 'Pareja', 22, 'https://casadiromavlc.com/wp-content/uploads/2019/03/toscana-1080x675.jpg'),
(16, 'Nueva Zelanda', 'Viaje orientado a descubrir escenarios espectaculares entre montañas, fiordos y costas salvajes. Pensado para viajeros que buscan aventura moderada, paisajes cinematográficos y contacto constante con la naturaleza, todo con una planificación que maximiza cada jornada.', '2026-03-18', '2026-04-02', 3700, 1, 'Solitario', 12, 'https://prd-webrepository.firabarcelona.com/wp-content/uploads/sites/69/2023/01/02123956/istock-1154591818.jpeg'),
(17, 'Egipto', 'Experiencia cultural centrada en la historia antigua, recorriendo templos, pirámides y ciudades legendarias. El viaje ofrece contexto histórico, visitas guiadas y tiempo para asimilar la magnitud de una civilización que sigue despertando fascinación en todo el mundo.', '2026-02-05', '2026-02-14', 2400, 1, 'Grupo', 30, 'https://content-viajes.nationalgeographic.com.es/medio/2024/11/27/egipto_95348746_269518164_241127144655_800x800.webp'),
(18, 'Bali', 'Estancia enfocada en el equilibrio personal, la cultura local y la naturaleza exuberante. Ideal para quienes buscan un viaje introspectivo, con templos, arrozales y momentos de calma, combinando actividades suaves con tiempo libre para la reflexión personal.', '2026-06-01', '2026-06-12', 2300, 1, 'Solitario', 14, 'https://viajeronomada.com/wp-content/uploads/2022/06/dondealojarseenbali-800x534.jpg'),
(19, 'Nueva York', 'Inmersión completa en una de las ciudades más dinámicas del mundo. El viaje combina visitas a iconos culturales, barrios diversos y tiempo libre para explorar según intereses personales, ofreciendo una experiencia intensa, variada y perfectamente organizada.', '2026-03-01', '2026-03-08', 2000, 1, 'Grupo', 35, 'https://www.civitatis.com/f/estados-unidos/nueva-york/galeria/carteles-publicitarios-times-square.jpg'),
(20, 'Escocia', 'Ruta que recorre castillos, paisajes verdes y pueblos con fuerte identidad cultural. Pensado para disfrutar de la historia, la música tradicional y la naturaleza, el viaje equilibra visitas guiadas con trayectos escénicos y momentos de descanso.', '2026-04-20', '2026-04-30', 2600, 1, 'Pareja', 16, 'https://losdosviajeros.com/img/escocia/castillo-eilean-donan.jpg'),
(21, 'Canadá', 'Viaje enfocado en grandes espacios naturales, parques nacionales y fauna en libertad. Ideal para quienes buscan tranquilidad, rutas panorámicas y actividades al aire libre, disfrutando de un entorno seguro, organizado y visualmente impresionante.', '2026-06-15', '2026-06-30', 3400, 1, 'Solitario', 10, 'https://media.iatiseguros.com/wp-content/uploads/2018/06/04005653/que-hacer-canada-7.jpg'),
(22, 'Grecia', 'Recorrido cultural que une historia antigua, paisajes mediterráneos y gastronomía local. Pensado para disfrutar en compañía, el viaje ofrece equilibrio entre visitas a yacimientos históricos, paseos costeros y tiempo libre en entornos tradicionales.', '2026-05-20', '2026-05-30', 2500, 1, 'Pareja', 20, 'https://www.crucerosislasgriegas.com/descubre/wp-content/uploads/descubriendo-las-islas-mas-populares-de-grecia.jpg'),
(23, 'Perú', 'Experiencia centrada en civilizaciones precolombinas, paisajes andinos y tradiciones vivas. El viaje combina rutas culturales, caminatas moderadas y gastronomía local, ofreciendo una visión profunda del país con una organización pensada para el viajero.', '2026-07-01', '2026-07-15', 3100, 1, 'Grupo', 26, 'https://www.peru.travel/Contenido/AcercaDePeru/Imagen/es/1/0.0/Principal/Machu%20Picchu.jpg'),
(24, 'Noruega', 'Viaje pensado para contemplar paisajes del norte europeo entre fiordos, montañas nevadas y pueblos costeros. Ideal para quienes buscan tranquilidad, naturaleza imponente y experiencias únicas como avistamiento de auroras boreales, recorridos escénicos y contacto directo con entornos poco alterados.', '2026-01-10', '2026-01-20', 3300, 1, 'Solitario', 12, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/90/45/f3/a-noruega-fica-no-norte.jpg'),
(25, 'Portugal', 'Escapada perfecta para disfrutar del océano Atlántico, ciudades con encanto y una gastronomía muy cuidada. El viaje combina paseos relajados, visitas culturales y tiempo libre para compartir experiencias, creando un equilibrio ideal entre descanso y descubrimiento.', '2026-06-05', '2026-06-13', 1800, 1, 'Pareja', 24, 'https://ssl.tzoo-img.com/images/tzoo.20775.0.831085.Porto.jpg');